import { Product } from './Product';

  export const PRODUCTS:Product[] = [
      { businessUserName:"Nike", 
        prodname: "Sport Shoes", 
        prodID: 1,
        price: 99.99, 
        image: "/assets/img/phones/nexus-s.0.jpg", 
        ProductDescription: "Nice Shoes", 
        Category: "Shoes", 
        Quantity: 50},

      { businessUserName:"Adidas", 
        prodname: "Pink T-shirt", 
        prodID: 2, 
        price: 109.99, 
        image: "/assets/img/phones/dell-venue.0.jpg", 
        ProductDescription: "Nice T-shirt", 
        Category: "T-shirts", 
        Quantity: 50},

      { businessUserName:"Nada Ashraf", 
        prodname: "Green Hoodie",
        prodID: 3,         
        price: 89.99, 
        image: "/assets/img/phones/droid-2-global-by-motorola.0.jpg", 
        ProductDescription: "Nice Green Hoodie", 
        Category: "Hoodies", 
        Quantity: 50},

      { businessUserName:"H&M",         
        prodname: "Grey Sweat Pants", 
        prodID: 4, 
        price: 129.99, 
        image: "/assets/img/phones/droid-pro-by-motorola.0.jpg", 
        ProductDescription: "Nice Grey Sweat Pants", 
        Category: "Sweat Pants", 
        Quantity: 50},

      { businessUserName:"Adidas",
        prodname: "Purple BackPack",
        prodID: 5,  
        price: 119.99, 
        image: "/assets/img/phones/motorola-bravo-with-motoblur.0.jpg", 
        ProductDescription: "Nice Purple BackPack", 
        Category: "BackPacks", 
        Quantity: 50},

      { businessUserName: "Activ",       
        prodname: "Dina BackPack", 
        prodID: 6,
        price: 139.99, 
        image: "/assets/img/phones/motorola-defy-with-motoblur.0.jpg", 
        ProductDescription: "Nice Dina BackPack", 
        Category: "BackPacks", 
        Quantity: 50},
  ]